### ISSUE TITLE
Modrinth: Download fails for files without `env`

### ISSUE THREAD

**Issue by ChrisJAllan** [itzg/mc-image-helper#260]
The [Modrinth docs](https://docs.modrinth.com/docs/modpacks/format_definition/#env-optional) shows `env` as optional, but the download fails if it is not present:

```
[mc-image-helper] 19:16:26.108 INFO  : Installing version 1.5.8 of The Lost Era Modpack
[mc-image-helper] 19:16:26.969 ERROR : 'install-modrinth-modpack' command failed. Version is 1.32.5
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "me.itzg.helpers.modrinth.model.ModpackIndex$ModpackFile.getEnv()" is null
	at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.lambda$processModpackFiles$13(InstallModrinthModpackCommand.java:351)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(Unknown Source)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at reactor.core.publisher.FluxIterable$IterableSubscription.hasNext(FluxIterable.java:271)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:187)
	at reactor.core.publisher.FluxStream.subscribe(FluxStream.java:69)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:102)
		at reactor.core.publisher.Mono.block(Mono.java:1712)
		at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.processModpack(InstallModrinthModpackCommand.java:167)
		at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.call(InstallModrinthModpackCommand.java:126)
		at me.itzg.helpers.modrinth.InstallModrinthModpackCommand.call(InstallModrinthModpackCommand.java:50)
		at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
		at picocli.CommandLine.access$1500(CommandLine.java:148)
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
		at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
		at picocli.CommandLine.execute(CommandLine.java:2170)
		at me.itzg.helpers.McImageHelper.main(McImageHelper.java:149)
[init] ERROR failed to install Modrinth modpack
```

**Comment by itzg** [comment]
Thanks. If it's not present, so you think it should be assumed a client-only or both mod? The docs don't seem to explain a default semantic.

**Comment by ChrisJAllan** [comment]
In this instance it should be required for both. Not sure if that's universal, or if it should be taken from the mod-wide setting seen on the page:
![image](https://github.com/itzg/mc-image-helper/assets/9275775/3f037fe8-542c-4eff-b9cf-d5cb0a6b699e)

**Comment by itzg** [comment]
The page would be getting that from the "env", so from that it seems when absent it implies required for both. Thanks for the investigation.
