### ISSUE TITLE
Currupted .purpur-manifest.json results in an bootloop

### ISSUE THREAD

**Issue by lucsoft** [itzg/mc-image-helper#336]
```
me.itzg.helpers.errors.GenericException: Failed to load manifest: Failed to load existing manifest from /data/.purpur-manifest.json
	at me.itzg.helpers.purpur.InstallPurpurCommand.loadOldManifest(InstallPurpurCommand.java:213)
	at me.itzg.helpers.purpur.InstallPurpurCommand.call(InstallPurpurCommand.java:96)
	at me.itzg.helpers.purpur.InstallPurpurCommand.call(InstallPurpurCommand.java:35)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:157)
Caused by: me.itzg.helpers.files.ManifestException: Failed to load existing manifest from /data/.purpur-manifest.json
	at me.itzg.helpers.files.Manifests.load(Manifests.java:123)
	at me.itzg.helpers.purpur.InstallPurpurCommand.loadOldManifest(InstallPurpurCommand.java:200)
	... 11 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4916)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4818)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3637)
	at me.itzg.helpers.files.Manifests.load(Manifests.java:121)
	... 12 common frames omitted
```

**Comment by itzg** [comment]
Thanks for reporting this. I should just have all the manifest loading log the error error and treat as missing.
