### ISSUE TITLE
Failed to locate Forge installer needs to be more descriptive

### ISSUE THREAD

**Issue by itzg** [itzg/mc-image-helper#365]
[Discussed in discord](https://discord.com/channels/660567679458869252/660571171732848651/1185757863143018577)

```
[mc-image-helper] 01:37:16.961 INFO  : Downloading Forge installer 1.37.3 for Minecraft 1.20.1

[mc-image-helper] 01:37:18.125 ERROR : 'install-forge' command failed. Version is 1.37.3

me.itzg.helpers.errors.GenericException: Failed to locate forge installer

    at me.itzg.helpers.forge.ForgeInstallerResolver.download(ForgeInstallerResolver.java:96)

    at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:85)

    at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:103)

    at me.itzg.helpers.forge.InstallForgeCommand.call(InstallForgeCommand.java:19)

    at picocli.CommandLine.executeUserObject(CommandLine.java:2041)

    at picocli.CommandLine.access$1500(CommandLine.java:148)

    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)

    at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)

    at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)

    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)

    at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)

    at picocli.CommandLine.execute(CommandLine.java:2170)

    at me.itzg.helpers.McImageHelper.main(McImageHelper.java:157)

[init] ERROR failed to install Forge
```

**Comment by halvors** [comment]
I experienced something similar, not sure if it should be a separate issue or not?

[mc-image-helper] 10:10:14.443 ERROR : 'install-neoforge' command failed. Version is 1.37.4
java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 7
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4861)
	at java.base/java.lang.String.substring(String.java:2830)
	at me.itzg.helpers.forge.NeoForgeInstallerResolver.lambda$resolve$0(NeoForgeInstallerResolver.java:60)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at me.itzg.helpers.forge.NeoForgeInstallerResolver.resolve(NeoForgeInstallerResolver.java:64)
	at me.itzg.helpers.forge.ForgeInstaller.install(ForgeInstaller.java:57)
	at me.itzg.helpers.forge.InstallNeoForgeCommand.call(InstallNeoForgeCommand.java:87)
	at me.itzg.helpers.forge.InstallNeoForgeCommand.call(InstallNeoForgeCommand.java:19)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:157)
[init] ERROR failed to install Forge

This seems to be related to https://maven.neoforged.net/ path now being https://maven.neoforged.net/#/

**Comment by itzg** [comment]
@halvors please write up a new issue and provide the inputs you used.
