### ISSUE TITLE
Failed to resolve `launchermeta.mojang.com` on server with only an ipv6 address.

### ISSUE THREAD

**Issue by smitssjors** [itzg/mc-image-helper#498]
I am currently running into an issue where the `resolve-minecraft-version` command fails due to the following exception:

```
reactor.core.Exceptions$ReactiveException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'launchermeta.mojang.com' [A(1)] and search domain query for configured domains failed as well: [.]
```

This seems to only happen on a host with only an ipv6 address and no ipv4 address. If I add an ipv4 address to the host it works as expected.

Both `dig launchermeta.mojang.com` and `curl -sL https://launchermeta.mojang.com/mc/game/version_manifest_v2.json` work as expected.

You can test this yourself by spinning up a Hetzner cloud VPS and only giving it an ipv6 address.

Full logs:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-x--- 2 1000 1000 4096 Dec 14 21:23 /data'
[init] Resolving type given VANILLA
[mc-image-helper] 14:20:11.258 ERROR : 'resolve-minecraft-version' command failed. Version is 1.40.6
reactor.core.Exceptions$ReactiveException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'launchermeta.mojang.com' [A(1)] and search domain query for configured domains failed as well: [.]
	at reactor.core.Exceptions.propagate(Exceptions.java:410)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:102)
	at reactor.core.publisher.Mono.block(Mono.java:1779)
	at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:26)
	at me.itzg.helpers.versions.ResolveMinecraftVersionCommand.call(ResolveMinecraftVersionCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:161)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:104)
		... 12 common frames omitted
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'launchermeta.mojang.com' [A(1)] and search domain query for configured domains failed as well: [.]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1150)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1097)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:455)
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:70)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:524)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.resolver.dns.DnsQueryContext.finishFailure(DnsQueryContext.java:343)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:278)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:156)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:408)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [6948: /8.8.4.4:53] DefaultDnsQuestion(launchermeta.mojang.com. IN A) query '6948' via UDP timed out after 5000 milliseconds (no stack trace available)
```

**Comment by smitssjors** [comment]
Looking a but further, it seems like the problem is that the DNS resolver is trying to use the nameserver at `8.8.4.4`. If I run `dig launchermeta.mojang.com @8.8.4.4` I also get an error.

A fix might be to instruct netty to use the nameserver specified in `/etc/resolv.conf`.

**Comment by smitssjors** [comment]
This seems to be related to my docker setup so I'll close for now

**Comment by smitssjors** [comment]
I've been debugging a bunch and by creating a ipv6 network in docker (https://docs.docker.com/engine/daemon/ipv6/) the DNS issue is solved and docker correctly gets the nameservers from the host. 

However, now the issue is that netty _randomly_ (https://github.com/netty/netty/issues/14278) picks and address (either v4 or v6) and thus sometimes it works and all goes well (i.e. the server downloads and starts, but authentication fails :) ). Otherwise an `no route to host` exception is thrown.

My guess is that the only way of properly dealing with this is to disable ipv4 in docker but it seems like they are still working on this (https://github.com/moby/moby/issues/32850).

The docker image is still awsome nonetheless
